name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Установка UV
        run: python -m pip intall uv

      - name: Установка зависимостей
        run: uv sync

      - name: Запуск автотестов
        run: uv run pytest -v --cov-report term-missing --cov=src --cov-branch